[build]
  # Directorio de publicación (la raíz del proyecto)
  publish = "."

[[redirects]]
  # SPA routing - todas las rutas van al index.html
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  # Admin panel routing
  from = "/admin/*"
  to = "/admin.html"
  status = 200

[[redirects]]
  # Panel routing  
  from = "/panel/*"
  to = "/panel.html"
  status = 200

[[redirects]]
  # Dashboard routing
  from = "/dashboard/*"
  to = "/mi_tablero.html"
  status = 200

[[redirects]]
  # PDF viewer routing
  from = "/viewer/*"
  to = "/espacio.html"
  status = 200

[[headers]]
  # Headers de seguridad para todos los archivos
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff" 
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

[[headers]]
  # Headers específicos para JavaScript modules
  for = "*.js"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000"

[[headers]]  
  # Headers para Service Worker
  for = "/sw.js"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"
    Cache-Control = "public, max-age=0, must-revalidate"
    Service-Worker-Allowed = "/"

[[headers]]
  # Headers para archivos PDF
  for = "*.pdf" 
  [headers.values]
    Content-Type = "application/pdf"
    Cache-Control = "public, max-age=86400"

[[headers]]
  # Headers para CSS
  for = "*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=31536000"

# Configuración de formularios (si se necesitan en el futuro)
[forms]
  settings = { }

# Configuración de funciones (para futuras expansiones)
[functions]
  directory = "netlify/functions/"